# -*- coding: utf-8 -*-
"""myapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tfFt3k4hu2OrbAy1sY3oTYvbU1CUXAhR
"""

import sqlite3
import pandas as pd
import streamlit as st
from PIL import Image
import numpy as np

# Create dataframe
data = np.random.randn(20,3)
d = pd.DataFrame(data)
d.columns=['a','b','c']

# Print title
st.title('My first web app')

# Print logo
image = Image.open('Logo-KDT-JU.webp') # Load the image from disk
st.image(image)

# Download button
@st.cache # IMPORTANT: Cache the conversion to prevent computation on every rerun
def convert_df(d):
  return d.to_csv().encode('utf-8')
st.download_button(label="mycsv",data=convert_df(d), file_name='d.csv', mime='text/csv',)

# Select button
option = st.selectbox('Column', ['a', 'b', 'c'])

# Bar chart
st.bar_chart(d)

# Dataframe
st.dataframe(d)
