# -*- coding: utf-8 -*-
"""Proj_pr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDmf3QaihkCwSQuSFuMCXaTHUV_51Byz
"""

import pandas as pd
countries = pd.read_excel('countries.xlsx')

"""For this step, the user will be asked to input a country name, which will be validated within the list of countries, gathered in a dictionary. For testing, the selected country will be Spain (ES)."""

# Country acronyms dictionary
country_acronyms = {'Belgium': 'BE', 'Bulgaria': 'BG', 'Czechia': 'CZ', 'Denmark': 'DK', 'Germany':
'DE', 'Estonia': 'EE', 'Ireland': 'IE','Greece': 'EL', 'Spain': 'ES', 'France': 'FR', 'Croatia':
'HR', 'Italy': 'IT', 'Cyprus': 'CY', 'Latvia': 'LV', 'Lithuania': 'LT','Luxembourg': 'LU',
'Hungary': 'HU', 'Malta': 'MT', 'Netherlands': 'NL', 'Austria': 'AT', 'Poland': 'PL', 'Portugal':
'PT','Romania': 'RO', 'Slovenia': 'SI', 'Slovakia': 'SK', 'Finland': 'FI', 'Sweden': 'SE'}

name = input('Insert a country name: ')
while name not in countries['Country'].tolist():
    name = input('Choose a valid country: ')

for k in country_acronyms.keys():
  if k == name:
    print(country_acronyms[name])

c=countries['Country'].tolist()
option = st.selectbox('Countries', c)