# -*- coding: utf-8 -*-
"""Proj_pr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDmf3QaihkCwSQuSFuMCXaTHUV_51Byz
"""

import pandas as pd
import sqlite3
import streamlit as st
from PIL import Image
"""For this step, the user will be asked to input a country name, which will be validated within the list of countries, gathered in a dictionary. For testing, the selected country will be Spain (ES)."""

# Country acronyms dictionary
country_acronyms = {'Belgium': 'BE', 'Bulgaria': 'BG', 'Czechia': 'CZ', 'Denmark': 'DK', 'Germany':
'DE', 'Estonia': 'EE', 'Ireland': 'IE','Greece': 'EL', 'Spain': 'ES', 'France': 'FR', 'Croatia':
'HR', 'Italy': 'IT', 'Cyprus': 'CY', 'Latvia': 'LV', 'Lithuania': 'LT','Luxembourg': 'LU',
'Hungary': 'HU', 'Malta': 'MT', 'Netherlands': 'NL', 'Austria': 'AT', 'Poland': 'PL', 'Portugal':
'PT','Romania': 'RO', 'Slovenia': 'SI', 'Slovakia': 'SK', 'Finland': 'FI', 'Sweden': 'SE'}


c=list(country_acronyms.keys)
option = st.selectbox('Countries', c)
