# -*- coding: utf-8 -*-
"""Proj_pr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDmf3QaihkCwSQuSFuMCXaTHUV_51Byz
"""

import sqlite3
import pandas as pd
import streamlit as st
from PIL import Image

# Country acronyms dictionary
country_acronyms = {'Belgium': 'BE', 'Bulgaria': 'BG', 'Czechia': 'CZ', 'Denmark': 'DK', 'Germany':
'DE', 'Estonia': 'EE', 'Ireland': 'IE','Greece': 'EL', 'Spain': 'ES', 'France': 'FR', 'Croatia':
'HR', 'Italy': 'IT', 'Cyprus': 'CY', 'Latvia': 'LV', 'Lithuania': 'LT','Luxembourg': 'LU',
'Hungary': 'HU', 'Malta': 'MT', 'Netherlands': 'NL', 'Austria': 'AT', 'Poland': 'PL', 'Portugal':
'PT','Romania': 'RO', 'Slovenia': 'SI', 'Slovakia': 'SK', 'Finland': 'FI', 'Sweden': 'SE'}


c=list(country_acronyms.keys())
option = st.selectbox('Countries', c)

conn = sqlite3.connect('ecsel_database.db')
cur=conn.cursor()
cur.execute("""
SELECT shortName, name, activityType, organizationURL, ecContribution) AS total_grants
FROM participants
JOIN projects ON organizationID = organizationID
WHERE country = 'selected_country'
GROUP BY shortName, name, activityType, organizationURL
ORDER BY ecContribution desc
""")

conn.commit()
cur.close()
conn.close()
